### ISSUE TITLE
  buckysroom.org doesn't exist anylonger

### ISSUE THREAD

**Issue by satang500** [buckyroberts/Source-Code-from-Tutorials#86]
I'm testing python web crawler chapter 25-27, but 
https://buckysroom.org/trade/ web page does not exist anymore.
I've been looking for similar web sites which has pages, but couldn't find it yet.
Could you let me know a good web site so that I can test the code in github?

**Comment by satang500** [comment]
found

**Comment by JustGregory-zz** [comment]
Technically, it would be nice if you had said what the solution is, instead of only closing with a one-word closure...

**Comment by Rahuljha330** [comment]
bros why does't buckysroom.org exists anymore

**Comment by Psyborgg** [comment]
newbie alert :)

**Comment by kothariharsh** [comment]
Dude, can you please tell the name of the webpage that will be helpful

**Comment by mikulabc** [comment]
@buckyroberts same here, was following youtube tutorials and got stuck here https://youtu.be/GQiLweAoxgQ?list=PL6gx4Cwl9DGAcbMi1sH6oAMk4JHw91mC_&t=352

**Comment by supolmusa** [comment]
> @buckyroberts same here, was following youtube tutorials and got stuck here https://youtu.be/GQiLweAoxgQ?list=PL6gx4Cwl9DGAcbMi1sH6oAMk4JHw91mC_&t=352

Same here.

**Comment by Naahun** [comment]
> found

Which?

**Comment by br4dd** [comment]
GUYS COULD ANYONE FIND BUCKY? WE NEED TO REVIVE HIS WEBSITE, WE LEARN FROM HIS SOURCES. :( PLEASE

**Comment by jhecht99** [comment]
ok...everybody relax...YOU DON'T NEED BUCKYSROOM......any image in any website will do.....for example, go to newsmax.com.....you will see articles and various images....right click on any image and copy the image address, just like Bucky says....then continue with the tutorial....it is simple and it works...trust me....

**Comment by neo-alkhwarizmi** [comment]
i think what was on buckysroom website is now in his github so just try to visit his github and may be you will find what ever you are looking for

**Comment by ObsidianMaximus** [comment]
Found his website?
From his videos, i got this but it doesnt work - https://thenewboston.com/

**Comment by rvignes42** [comment]
https://developer.thenewboston.com/ Try this website fellas

**Comment by 501hasan** [comment]
https://x.com/Armotheretired/status/1342254516952051712
someone in the youtube comments posted this X link and it works
